---
title: "Investigating the Effects of Choice on Mitigating Anxiety"
authors: Ari Astawa, August Gonzales, Saksham Jain, Harry Le, Leo Sharwood, Blake Walker
format:
    html:
        embed-resources: true
editor: visual
---

## Abstract

Being able to mitigate anxiety associated with any given activity is always a desirable outcome. Considering the frequency of anticipatory anxiety in daily life, it is worth investigating whether the ability to choose—and thus exert some level of control—can reduce detrimental emotional responses. The analysis in this report finds that choice does not play a significant role in managing or reducing the effects of anxiety that precedes an activity with perceived displeasure.

## Initial Data Analysis

The data was sourced through an experimental survey examining 337 participants on the effects of choice on socially acquired nocebo effects in the context of cybersickness in Virtual Reality (VR). Overall, the dataset was well structured and documented with sound integrity.

This investigation has a unique focus on anxiety. Experimentally, our report examines how choice plays a role in modulating the level of anxiety participants have to experiencing VR having understood possible symptoms associated with the activity. The variables of Choice, VR Environment, VR Anxiety (Level), Baseline/Active/Delta Anxiety, and Age were all considered. In particular, a reclassification of Age from a quantitative continuous variable to a qualitative nominal was done. All other data types were maintained: Choice as qualitative nominal, VR Environment as qualitative nominal, VR Anxiety as quantitative discrete, and B/A/D Anxiety as quantitative discrete.

This dataset and analysis is only somewhat limited by the sample size, along with the discrepancies found between the 3 experiments. We assume within this report that pooled experimental data is consistent between the separate trials. Additionally, there was minor data cleaning, including, but not limited to anxiety levels that were outside of the possible range. Furthermore, the data was selected down to the age groups between 15 and 40 so as to be more representative of the targeted survey bloc.

## Analysis

::: panel-tabset
## Choice & Environment vs. Δ VR Anxiety, Separation by Age Ranges

{{< embed Graphs.qmd#ce-vranx-age >}}

## Choice & Environment vs. Δ VR Anxiety, No Separation by Age Ranges

{{< embed Graphs.qmd#ce-vranx-noage >}}

## Choice Only and Environment Only

{{< embed Graphs.qmd#separate-ce-vranx >}}
:::

-   Choice does not affect level of anxiety
-   Environment does not



Our analysis within this report found that there was no relationship between either the ability to choose or the VR environment to the level of anxiety change. However, it is notable that the range for change in anxiety for those experiencing a sunny environment was somewhat greater than those with a snowy environment. This is more likely to be a result of natural variation in the dataset though; there is unlikely to be an underlying mechanism for these results.

A more detailed look at the data finds that the mean change in anxiety in participants who were given the ability to choose was 2.096 compared to 1.955 for those who did not. This demonstrates that choice has no bearing on easing the amount of anxiety a person experiences with regards to a daunting activity that may cause side effects like cybersickness.


Our analysis within this report found that typically no anxiety change relationship could be found between environments. Although, notably the range for change in anxiety for those with a sunny environment was much greater than those with a snowy environment, indicating a small correlation. Moreover, the analysis conveyed that the spreads of the data decreased for both environments when given the choice to choose. As such the environment the user experiences has little association with the change in anxiety, although when given a choice a more decisive result may occur although the data is not strong enough to confirm this.

The data conveyed that the change in anxiety levels between users of sunny, and snowy environments varied by miniscule amounts. This was concluded because the median change among all age groups for sunny environments was 1.4, while snowy was 1.6, revealing that snowy environments had a slightly higher change. Furthermore, the average range of IQR was 3.6 for sunny environments, and 3.1 for snowy. This implies that snowy environments lower IQR were resultant of a more decisive and consistent change. Hence, the small difference in median, and IQR range indicate that system environment has little to no correlation with anxiety level changes.

However, the data implied that there would be small change resulting from a choice, as the average median for participants who chose was 1.833 on the anxiety test while it was 1.5 for those who did not, illustrating that the choice itself possibly increased anxiety levels. Whereas the average range of IQR for those who chose was 3.1, whereas it was 3.9 for those who did not get to choose.

To conclude, there is a negligible influence on change in anxiety levels due to the system environment, as the average anxiety levels of different environments are very similar. Although factors apart from system environment, and choice might have played a larger role in the resultant anxiety level due to the relatively low change found in the respective variables (Kwon, 2020). Furthermore, our findings reflect that choice had a small effect, producing narrower max, min's, and IQR's, conveying a possible relationship. Where someone's previous experience might manipulate the variability in the data due to experiences from similar environments (Matteo Girondini et al., 2023). We came to a consensus that our findings reflect that volition might have an impact on the variability of anxiety level, where a lack of choice leads to higher variability while having a choice leads to more consistent levels. Although the changes are small they do indicate a psychological variability in the response. Whereas the actual environment won't impact changing anxiety levels.

## Professional Standard of Report

Throughout the report every member maintained respect for each others privacy, and confidentiality along with professionalism, letting each other do there own dedicated work towards our data story. Additionally, ethical principles were obeyed, with truthfulness and integrity of our work progress, keeping everyone accountable for their own actions.

------------------------------------------------------------------------

## References & Acknowledgements

{{< include "Meetings and Contributions.qmd" >}}

-   all resources used (eg url of stack overflow, url of Ed post, date and details of drop-in session with tutor)

{{< include "Acknowledgements and Resources.qmd" >}}

-   an AI usage statement explaining how AI was used, the name and version of AI tools used, the date/s of use of the AI tools and a link to the entire prompt session used to inform the report. If no AI was used, this must be made explicit.
